use_frameworks!

platform :ios, '10.0'

target 'Environment_Example' do
  pod 'Environment', :path => '../'

  target 'Environment_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
